name: clang-format Check

on:
  push:
    paths:
      - '.clang-format'
      - 'app/src/main/cpp/**'
      - '!**/CMakeLists.txt'

  pull_request:
    paths:
      - '.clang-format'
      - 'app/src/main/cpp/**'
      - '!**/CMakeLists.txt'

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          sparse-checkout: app/src/main/cpp

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.18.0
        with:
          check-path: app/src/main/cpp
          exclude-regex: (ThirdParty)
